### ISSUE TITLE
Question about the accuracy of KWT-1, 2, 3

### ISSUE THREAD

**Issue by jihwanpark-airspeech** [HolgerBovbjerg/data2vec-KWS#2]
On your results table (https://github.com/HolgerBovbjerg/data2vec-KWS#results), as the kwt parameter increases, the accuracy decreases.
- KWT-1 (full) : 0.9638
- KWT-2 (full) : 0.9498
- KWT-3 (full) : 0.9079 

As far as I know, KWT performs better on KWT-3 than on KWT-1 in V2-35. (https://arxiv.org/pdf/2104.00769v3.pdf, Table 3)
Why do you think the performance is lower in KWT 3 than in KWT 1? Is there any difference between KWT and settings?

**Comment by HolgerBovbjerg** [comment]
Hi,
The only discrepancy that I know of between the baseline in my work and the original models is the augmentation during supervised training. Here I only use SpecAugment. 
One reason the larger models score lower is that they might need more data for training (which could be solved by using more augmentation). However, I have not tested this.

**Comment by jihwanpark-airspeech** [comment]
Thanks!
