### ISSUE TITLE
A question on the code

### ISSUE THREAD

**Issue by tomato18463** [HolgerBovbjerg/data2vec-KWS#6]
Hi,

I note the transpose in [this line](https://github.com/HolgerBovbjerg/data2vec-KWS/blob/main/models/Data2Vec.py#L115) seems not do anything. Is something wrong with this line, or is it just a typo?

Thanks!

**Comment by l2009312042** [comment]
i think this line should be  
 y = F.instance_norm(y.transpose(1, 2)).transpose(1, 2)
